//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strzelnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class BRONIE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BRONIE()
        {
            this.WYPOZYCZENIA = new HashSet<WYPOZYCZENIA>();
        }
    
        public int ID { get; set; }
        public string PRODUCENT { get; set; }
        public string MODEL { get; set; }
        public int TYP { get; set; }
        public int AMUNICJA { get; set; }
        public decimal CENA_WYPOZYCZENIA { get; set; }
    
        public virtual AMUNICJA AMUNICJA1 { get; set; }
        public virtual BRONIE_TYP BRONIE_TYP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WYPOZYCZENIA> WYPOZYCZENIA { get; set; }
    }
}
