//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strzelnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARNETY
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KARNETY()
        {
            this.KLIENCI = new HashSet<KLIENCI>();
        }
    
        public int ID { get; set; }
        public int RODZAJ_KARNETU { get; set; }
        public System.DateTime DATA_WAZNOSCI { get; set; }
    
        public virtual KARNETY_RODZAJ KARNETY_RODZAJ { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KLIENCI> KLIENCI { get; set; }
    }
}
