//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strzelnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class KARNETY_RODZAJ
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KARNETY_RODZAJ()
        {
            this.KARNETY = new HashSet<KARNETY>();
        }
    
        public int ID { get; set; }
        public string NAZWA { get; set; }
        public int PROCENT_ULGI { get; set; }
        public decimal CENA_KARNETU { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KARNETY> KARNETY { get; set; }
    }
}
