//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Strzelnica
{
    using System;
    using System.Collections.Generic;
    
    public partial class WYPOZYCZENIA
    {
        public int ID { get; set; }
        public int ID_KLIENTA { get; set; }
        public Nullable<int> ID_TRENERA { get; set; }
        public int ID_STANOWISKA { get; set; }
        public int ID_BRONI { get; set; }
        public Nullable<int> ILOSC_PAKIETOW_AMUNICJI { get; set; }
        public System.DateTime DATA_POCZATEK { get; set; }
        public System.DateTime DATA_KONIEC { get; set; }
    
        public virtual BRONIE BRONIE { get; set; }
        public virtual KLIENCI KLIENCI { get; set; }
        public virtual STANOWISKA STANOWISKA { get; set; }
        public virtual TRENERZY TRENERZY { get; set; }
    }
}
